/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package team5.risc.client;
import team5.risc.client.controller.LoginController;
import team5.risc.common.*;
import java.net.*;
import java.io.IOException;

import java.net.URL;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class GUIClient extends Application {

    @Override
    public void start(Stage stage) throws IOException {
        RISCServer riscServer = new RISCServer("127.0.0.1", 8999);
        Client client = new Client(riscServer, null);

        URL xmlResource = getClass().getResource("/ui/login.fxml"); 
        if (xmlResource == null) {
            System.out.print("No resource found");
            return;
        }

        FXMLLoader loader = new FXMLLoader(xmlResource);
        StackPane gp = loader.load();

        LoginController loginController = loader.<LoginController>getController();
        loginController.setClient(client);
        
        Scene scene = new Scene(gp, 640, 480);
        stage.setScene(scene);

        stage.show();
    }
}
