/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package team5.risc.client;
import team5.risc.common.*;
import java.net.*;
import java.io.IOException;

import java.net.URL;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class GUIClient extends Application {

    @Override
    public void start(Stage stage) throws IOException {
        URL xmlResource = getClass().getResource("/ui/login.xml"); 
        if (xmlResource == null) {
            System.out.print("No resource found");
            return;
        }
        Parent gp = FXMLLoader.load(xmlResource);
        Scene scene = new Scene(gp, 640, 480);
        stage.setScene(scene);
        stage.show();
    }
}
