/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package team5.risc.client;

import team5.risc.client.controller.LoginController;
import team5.risc.common.*;
import java.net.*;
import java.io.IOException;

import java.net.URL;
import java.util.List;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import javafx.scene.media.MediaPlayer;
import javafx.scene.media.Media;
import java.io.File;

public class GUIClient extends Application {

    public MediaPlayer mediaPlayer; 
    public void backgroundMusic() {
        Media sound = new Media(getClass().getResource("/sound/background.wav").toExternalForm());
        MediaPlayer mediaPlayer = new MediaPlayer(sound);
        mediaPlayer.play();
        mediaPlayer.setCycleCount(MediaPlayer.INDEFINITE);
    }

    
    @Override
    public void start(Stage stage) throws IOException {
        Parameters parameters = getParameters();
        List<String> rawArguments = parameters.getRaw();

        RISCServer riscServer = new RISCServer(
                rawArguments.get(0),
                Integer.parseInt(rawArguments.get(1)));

        Client client = new Client(riscServer, null);

        backgroundMusic();

        URL xmlResource = getClass().getResource("/ui/login.fxml");
        if (xmlResource == null) {
            System.out.print("No resource found");
            return;
        }

        FXMLLoader loader = new FXMLLoader(xmlResource);
        AnchorPane gp = loader.load();

        LoginController loginController = loader.<LoginController>getController();
        loginController.setClient(client);

        Scene scene = new Scene(gp, 600, 500);
        stage.setScene(scene);

        stage.show();
    }
}
